# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: root3287/dev_ros

build:
  stage: build
  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
      - apt-get update && apt-get dist-upgrade
  #   - apt update && apt -y install make autoconf
  before_script:
    - source /opt/ros/noetic/setup.sh
    - env | grep ros
  script:
    - premake5 gmake2
    - make -C workspace/
  artifacts:
    paths:
      - bin/Debug/linux-x86_64/
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - source /opt/ros/noetic/setup.sh
    - env | grep ros
  script:
    - echo "test"
